#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------
 
  version: '3.7'
  services:
    exercism:
      image: exercism-io--clojure

  #     labels:
  #       - "exercism=clojure"
      environment:
        - TOKEN=${EXERCISM_TOKEN}

      volumes:
        # This is where VS Code should expect to find your project's source code
        # and the value of "workspaceFolder" in .devcontainer/devcontainer.json
        - ..:/workspace
  #       - volume-vscode:/home/vscode
        - ~/.ssh:/tmp/.ssh-localhost:ro
  #       - /var/run/docker.sock:/var/run/docker.sock
  #       - ~/.gitconfig:/tmp/git/.gitconfig

      ports:
        - "4000:4000"

      # Overrides default command so things don't shut down after the process ends.
      command: /bin/bash -c "while sleep 1000; do :; done" 

  # volumes:
  #   volume-vscode:
  #     labels:
  #       - "exercism=clojure"